resources:
  jobs:
    dab_test_job:
      name: CustomerSuccess

      schedule:
        quartz_cron_expression: '44 37 8 * * ?'
        timezone_id: Europe/Amsterdam

      email_notifications:
        on_failure:
          - enter email address

      tasks:
        - task_key: FunctionApp1
          job_cluster_key: job_cluster
          notebook_task:
            notebook_path: ../FunctionApp/FunctionApp1.py  # Updated notebook path

        - task_key: FunctionApp2
          job_cluster_key: job_cluster
          notebook_task:
            notebook_path: ../FunctionApp/FunctionApp2.py  # Added second notebook task

      job_clusters:
        - job_cluster_key: job_cluster
          new_cluster:
            spark_version: 13.3.x-scala2.12
            node_type_id: Standard_D3_v2
            autoscale:
                min_workers: 1
                max_workers: 4
